# Generated by Django 4.2.9 on 2024-01-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="day", field=models.CharField(max_length=25),
        ),
    ]
