# Generated by Django 4.2.9 on 2024-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_complete_alter_question_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="day", field=models.DateTimeField(),
        ),
    ]
