# Generated by Django 4.2.9 on 2024-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_question_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
            ],
        ),
    ]
